spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/log?useUnicode=true&characterEncoding=utf_8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: info
    com.difu: debug
  file:
    name: log/blog.log
server:
  port: 8080
